"""Add punishment columns to Vehicle

Revision ID: 6674fd5b8e1f
Revises: 
Create Date: 2025-05-01 10:21:52.186969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6674fd5b8e1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('punishment_count', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('punishment_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'punishment_amount')
    op.drop_column('vehicles', 'punishment_count')
    # ### end Alembic commands ###
