"""Add created and updated at columns to Vehicle

Revision ID: b16df055435d
Revises: 6674fd5b8e1f
Create Date: 2025-05-01 10:37:19.327969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16df055435d'
down_revision: Union[str, None] = '6674fd5b8e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###
